baseURL: "https://dayops.ru"
languageCode: en-us
title: DayOps
theme: PaperMod

params:
  homeInfoParams:
    Title: DayOps.ru ![Logo](favi.png)
    Content: Всем привет! Добро пожаловать на мой блог, посвященный ИТ тематике. Я надеюсь, что здесь вы сможете найти полезную и интересную информацию для себя.
  socialIcons:
    - name: linkidin
      url: "https://github.com/splivak"
    - name: github
      url: "https://github.com/splivak"
    - name: kofi
      url: "https://github.com/splivak"
    - name: telegram
      url: "https://github.com/splivak"
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon32x32: "favi.png"
    
  
  defaultTheme: light
  ShowBreadCrumbs: true # навигация по постам
  ShowReadingTime: true # время чтения статьи
  ShowShareButtonns: true 
  ShowPostNavLinks: true # кнопки вперед/назад
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 30